/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TalentCardsRouteImport } from './routes/talent-cards'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OpeningsRouteImport } from './routes/openings'
import { Route as ForEmployersRouteImport } from './routes/for-employers'
import { Route as ForCandidatesRouteImport } from './routes/for-candidates'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamCandidateSearchRouteImport } from './routes/team/candidate-search'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiTeamSessionRouteImport } from './routes/api/team/session'
import { Route as ApiTeamLogoutRouteImport } from './routes/api/team/logout'
import { Route as ApiTeamLoginRouteImport } from './routes/api/team/login'
import { Route as ApiTeamCandidateSearchRouteImport } from './routes/api/team/candidate-search'
import { Route as ApiPublicTalentCardRequestRouteImport } from './routes/api/public/talent-card-request'
import { Route as ApiPublicFormSubmissionRouteImport } from './routes/api/public/form-submission'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentCardsRoute = TalentCardsRouteImport.update({
  id: '/talent-cards',
  path: '/talent-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsRoute = OpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => rootRouteImport,
} as any)
const ForEmployersRoute = ForEmployersRouteImport.update({
  id: '/for-employers',
  path: '/for-employers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCandidatesRoute = ForCandidatesRouteImport.update({
  id: '/for-candidates',
  path: '/for-candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamCandidateSearchRoute = TeamCandidateSearchRouteImport.update({
  id: '/team/candidate-search',
  path: '/team/candidate-search',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamSessionRoute = ApiTeamSessionRouteImport.update({
  id: '/api/team/session',
  path: '/api/team/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamLogoutRoute = ApiTeamLogoutRouteImport.update({
  id: '/api/team/logout',
  path: '/api/team/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamLoginRoute = ApiTeamLoginRouteImport.update({
  id: '/api/team/login',
  path: '/api/team/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamCandidateSearchRoute = ApiTeamCandidateSearchRouteImport.update({
  id: '/api/team/candidate-search',
  path: '/api/team/candidate-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTalentCardRequestRoute =
  ApiPublicTalentCardRequestRouteImport.update({
    id: '/api/public/talent-card-request',
    path: '/api/public/talent-card-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFormSubmissionRoute = ApiPublicFormSubmissionRouteImport.update({
  id: '/api/public/form-submission',
  path: '/api/public/form-submission',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/for-candidates': typeof ForCandidatesRoute
  '/for-employers': typeof ForEmployersRoute
  '/openings': typeof OpeningsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent-cards': typeof TalentCardsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/team/candidate-search': typeof TeamCandidateSearchRoute
  '/api/public/form-submission': typeof ApiPublicFormSubmissionRoute
  '/api/public/talent-card-request': typeof ApiPublicTalentCardRequestRoute
  '/api/team/candidate-search': typeof ApiTeamCandidateSearchRoute
  '/api/team/login': typeof ApiTeamLoginRoute
  '/api/team/logout': typeof ApiTeamLogoutRoute
  '/api/team/session': typeof ApiTeamSessionRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/for-candidates': typeof ForCandidatesRoute
  '/for-employers': typeof ForEmployersRoute
  '/openings': typeof OpeningsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent-cards': typeof TalentCardsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/team/candidate-search': typeof TeamCandidateSearchRoute
  '/api/public/form-submission': typeof ApiPublicFormSubmissionRoute
  '/api/public/talent-card-request': typeof ApiPublicTalentCardRequestRoute
  '/api/team/candidate-search': typeof ApiTeamCandidateSearchRoute
  '/api/team/login': typeof ApiTeamLoginRoute
  '/api/team/logout': typeof ApiTeamLogoutRoute
  '/api/team/session': typeof ApiTeamSessionRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/for-candidates': typeof ForCandidatesRoute
  '/for-employers': typeof ForEmployersRoute
  '/openings': typeof OpeningsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent-cards': typeof TalentCardsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/team/candidate-search': typeof TeamCandidateSearchRoute
  '/api/public/form-submission': typeof ApiPublicFormSubmissionRoute
  '/api/public/talent-card-request': typeof ApiPublicTalentCardRequestRoute
  '/api/team/candidate-search': typeof ApiTeamCandidateSearchRoute
  '/api/team/login': typeof ApiTeamLoginRoute
  '/api/team/logout': typeof ApiTeamLogoutRoute
  '/api/team/session': typeof ApiTeamSessionRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/for-candidates'
    | '/for-employers'
    | '/openings'
    | '/services'
    | '/sitemap.xml'
    | '/talent-cards'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/team/candidate-search'
    | '/api/public/form-submission'
    | '/api/public/talent-card-request'
    | '/api/team/candidate-search'
    | '/api/team/login'
    | '/api/team/logout'
    | '/api/team/session'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/for-candidates'
    | '/for-employers'
    | '/openings'
    | '/services'
    | '/sitemap.xml'
    | '/talent-cards'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/team/candidate-search'
    | '/api/public/form-submission'
    | '/api/public/talent-card-request'
    | '/api/team/candidate-search'
    | '/api/team/login'
    | '/api/team/logout'
    | '/api/team/session'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/for-candidates'
    | '/for-employers'
    | '/openings'
    | '/services'
    | '/sitemap.xml'
    | '/talent-cards'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/team/candidate-search'
    | '/api/public/form-submission'
    | '/api/public/talent-card-request'
    | '/api/team/candidate-search'
    | '/api/team/login'
    | '/api/team/logout'
    | '/api/team/session'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ForCandidatesRoute: typeof ForCandidatesRoute
  ForEmployersRoute: typeof ForEmployersRoute
  OpeningsRoute: typeof OpeningsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TalentCardsRoute: typeof TalentCardsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  TeamCandidateSearchRoute: typeof TeamCandidateSearchRoute
  ApiPublicFormSubmissionRoute: typeof ApiPublicFormSubmissionRoute
  ApiPublicTalentCardRequestRoute: typeof ApiPublicTalentCardRequestRoute
  ApiTeamCandidateSearchRoute: typeof ApiTeamCandidateSearchRoute
  ApiTeamLoginRoute: typeof ApiTeamLoginRoute
  ApiTeamLogoutRoute: typeof ApiTeamLogoutRoute
  ApiTeamSessionRoute: typeof ApiTeamSessionRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-cards': {
      id: '/talent-cards'
      path: '/talent-cards'
      fullPath: '/talent-cards'
      preLoaderRoute: typeof TalentCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings': {
      id: '/openings'
      path: '/openings'
      fullPath: '/openings'
      preLoaderRoute: typeof OpeningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-employers': {
      id: '/for-employers'
      path: '/for-employers'
      fullPath: '/for-employers'
      preLoaderRoute: typeof ForEmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-candidates': {
      id: '/for-candidates'
      path: '/for-candidates'
      fullPath: '/for-candidates'
      preLoaderRoute: typeof ForCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/candidate-search': {
      id: '/team/candidate-search'
      path: '/team/candidate-search'
      fullPath: '/team/candidate-search'
      preLoaderRoute: typeof TeamCandidateSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/session': {
      id: '/api/team/session'
      path: '/api/team/session'
      fullPath: '/api/team/session'
      preLoaderRoute: typeof ApiTeamSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/logout': {
      id: '/api/team/logout'
      path: '/api/team/logout'
      fullPath: '/api/team/logout'
      preLoaderRoute: typeof ApiTeamLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/login': {
      id: '/api/team/login'
      path: '/api/team/login'
      fullPath: '/api/team/login'
      preLoaderRoute: typeof ApiTeamLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/candidate-search': {
      id: '/api/team/candidate-search'
      path: '/api/team/candidate-search'
      fullPath: '/api/team/candidate-search'
      preLoaderRoute: typeof ApiTeamCandidateSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/talent-card-request': {
      id: '/api/public/talent-card-request'
      path: '/api/public/talent-card-request'
      fullPath: '/api/public/talent-card-request'
      preLoaderRoute: typeof ApiPublicTalentCardRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/form-submission': {
      id: '/api/public/form-submission'
      path: '/api/public/form-submission'
      fullPath: '/api/public/form-submission'
      preLoaderRoute: typeof ApiPublicFormSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ForCandidatesRoute: ForCandidatesRoute,
  ForEmployersRoute: ForEmployersRoute,
  OpeningsRoute: OpeningsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TalentCardsRoute: TalentCardsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  TeamCandidateSearchRoute: TeamCandidateSearchRoute,
  ApiPublicFormSubmissionRoute: ApiPublicFormSubmissionRoute,
  ApiPublicTalentCardRequestRoute: ApiPublicTalentCardRequestRoute,
  ApiTeamCandidateSearchRoute: ApiTeamCandidateSearchRoute,
  ApiTeamLoginRoute: ApiTeamLoginRoute,
  ApiTeamLogoutRoute: ApiTeamLogoutRoute,
  ApiTeamSessionRoute: ApiTeamSessionRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
